import type { HarnessFileState, ProjectScan, ReadinessScore } from "../types.js";

export function scoreReadiness(scan: ProjectScan): ReadinessScore {
  let score = 0;
  const strengths: string[] = [];
  const missing: string[] = [];
  const warnings: string[] = [];

  addHarness(scan.existingHarness.claudeMd, 18, "Maintainer-authored root CLAUDE.md exists", "No maintainer-authored root CLAUDE.md");
  addHarness(scan.existingHarness.codemap, 12, "Maintainer-authored CODEMAP.md exists", "No maintainer-authored CODEMAP.md / codebase map");
  addHarness(scan.existingHarness.aiIgnore, 10, "Maintainer-authored .aiignore exists", "No maintainer-authored .aiignore");
  addHarness(scan.existingHarness.claudeSettings, 10, "Maintainer-authored .claude/settings.json exists", "No maintainer-authored Claude settings/permissions");
  add(Boolean(scan.commands.build?.length), 10, "Build command detected", "No build command detected");
  add(Boolean(scan.commands.test?.length || scan.commands.lint?.length || scan.commands.typecheck?.length), 12, "Validation commands detected", "No test/lint/typecheck command detected");
  add(scan.codeGraph.entryPoints.length > 0, 8, "Code entry points detected", "No code entry points detected");
  add(scan.codeGraph.importEdges.length > 0 || scan.codeGraph.externalImports.length > 0, 8, "Import graph detected", "No import graph detected");
  add(scan.monorepo.detected ? scan.packages.length > 1 : true, 5, "Workspace/package layout detected", "Monorepo detected but packages are unclear");
  add(scan.languages.length > 0, 5, `Languages detected: ${scan.languages.join(", ")}`, "Could not detect languages");
  add(scan.existingHarness.skillsDir && !isOnlyAgentReadySkills(scan), 2, "Maintainer skills directory exists", "No maintainer-authored reusable skills directory");

  warnIfGenerated("CLAUDE.md", scan.existingHarness.claudeMd);
  warnIfGenerated("CODEMAP.md", scan.existingHarness.codemap);
  warnIfGenerated(".aiignore", scan.existingHarness.aiIgnore);
  warnIfGenerated(".claude/settings.json", scan.existingHarness.claudeSettings);

  if (scan.monorepo.detected && !scan.existingHarness.claudeMd.exists) warnings.push("Monorepo without CLAUDE.md: agents will waste context discovering structure.");
  if (scan.noisyPaths.length > 0 && !scan.existingHarness.aiIgnore.exists) warnings.push(`Noisy paths detected (${scan.noisyPaths.join(", ")}) but no .aiignore exists.`);
  if (scan.traits.hasHebrewOrRtl) strengths.push("Hebrew/RTL trait detected; RTL UI skill will be generated.");
  if (scan.databases.length > 0) strengths.push(`Database tooling detected: ${scan.databases.join(", ")}.`);

  return { score: Math.min(score, 100), strengths, missing, warnings };

  function add(condition: boolean, points: number, yes: string, no: string) {
    if (condition) {
      score += points;
      strengths.push(yes);
    } else {
      missing.push(no);
    }
  }

  function addHarness(file: HarnessFileState, points: number, yes: string, no: string) {
    add(file.countsAsMaintainerAuthored, points, yes, file.exists ? `${no} (existing file is agent-ready generated and needs maintainer review)` : no);
  }

  function warnIfGenerated(label: string, file: HarnessFileState) {
    if (file.generatedByAgentReady) warnings.push(`${label} was generated by agent-ready; it is not counted as maintainer-authored readiness until reviewed/customized.`);
  }
}

function isOnlyAgentReadySkills(scan: ProjectScan): boolean {
  return scan.existingHarness.skillsDir && !scan.existingHarness.claudeMd.countsAsMaintainerAuthored;
}
